apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yml
#- ingress.yml
# - service.yml

namespace: dev
resources:
- ../base
images:
- name: boonkwang/nginx
  newTag: cdbaec29a84c557ff6d9a3d2de77f0a95fd506c7
