apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
#- ingress.yaml
# - service.yaml

namespace: dev
resources:
- ../base
images:
- name: boonkwang/nginx
  newTag: 09f0d4a5e306a544a6e24036e834276ec9cd16a0
