apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yml
#- ingress.yml
# - service.yml

namespace: dev
resources:
- ../base
images:
- name: boonkwang/nginx