apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
#- ingress.yaml
# - service.yaml

namespace: dev
resources:
- ../base
images:
- name: boonkwang/nginx
  newTag: 91a5016ac5be6aef0a87f4153e6a60a4241681eb
