name: build docker

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set tag
        run: echo "TAG=$GITHUB_SHA" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Check tag env
        run: echo ${{ env.TAG }}
      -
        name: Check GITHUB REF NAME
        run: echo xxx $GITHUB_REF_NAME
      -
        name: Build and push
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ env.TAG }}

  update_tag:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set tag
        run: echo "TAG=$GITHUB_SHA" >> $GITHUB_ENV
      - name: condition 1
        if: github.ref.name == 'dev'
        run: echo "The operating system on the runner is $env:GITHUB_REF_NAME."